version: '3.7'

services:
  app:
    build: .
    container_name: acs_projects
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - .:/acs_projects
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
  proxy:
    container_name: acs_projects_proxy
    build:
      context: ./proxy
    environment:
      - TZ=Europe/Athens
    volumes:
      - static_data:/vol/acs_projects/static/
      - static_media:/vol/acs_projects/media/
    ports:
      - "7570:7570"
    depends_on:
      - app
  db:
    container_name: acs_projects_database
    image: postgres
    volumes:
      - postgres_projects_data:/var/lib/postgressql/data
    env_file:
      - .env
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "5430:5432"
  pg_admin:
    container_name: projects_pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LOGIN_PORT}
    ports:
      - "5560:5560"
volumes:
  static_data:
  static_media:
  postgres_projects_data: