# Generated by Django 4.2 on 2024-01-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_status_alter_projectfile_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
