# Generated by Django 4.2 on 2024-01-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_completion_date_project_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_completed',
        ),
    ]
