# Generated by Django 4.2 on 2024-01-29 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_project_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnote',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='projectnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
