# Generated by Django 4.2 on 2024-01-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todolist_created_at_todolist_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
